name: markdown-linting

on: [push]

jobs:
  lint_readme:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v2
      with:
        node-version: '18'

    - run: npm install -g markdownlint-cli2

    - run: markdownlint-cli2 --config .github/workflows/.markdownlint.json '**/*.md'

